<?php

namespace CatFacts;

use CatFacts\Api\Client;
use Http\Client\Common\Plugin\AddHostPlugin;
use Http\Client\Common\Plugin\AddPathPlugin;
use Http\Client\Common\Plugin\ErrorPlugin;
use Http\Client\Common\PluginClient;
use Http\Client\HttpClient;
use Http\Discovery\HttpClientDiscovery;
use Http\Discovery\UriFactoryDiscovery;

class ClientFactory
{
    public static function create(HttpClient $httpClient = null): Client
    {
        // Find a default HTTP client if none provided
        if (null === $httpClient) {
            $httpClient = HttpClientDiscovery::find();
        }

        // Decorates the HTTP client with some plugins
        $uri = UriFactoryDiscovery::find()->createUri('https://cat-fact.herokuapp.com');
        $pluginClient = new PluginClient($httpClient, [
            new ErrorPlugin(),
            new AddHostPlugin($uri),
        ]);

        // Instantiate an OpenApi client generated by Jane
        return Client::create($pluginClient);
    }
}
